name: Tests

on: [push]
  - "!**/*.md"

jobs:
  integration:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn
      - run: yarn test:ci
